//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItems
    {
        public int Id { get; set; }
        public int CartId { get; set; }
        public int FlowerId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Carts Carts { get; set; }
        public virtual FlowerProducts FlowerProducts { get; set; }
    }
}
