//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int FlowerId { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual FlowerProducts FlowerProducts { get; set; }
        public virtual Users Users { get; set; }
    }
}
