//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class flower_shopEntities : DbContext
    {
        public flower_shopEntities()
            : base("name=flower_shopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<flowers> flowers { get; set; }
        public virtual DbSet<order_items> order_items { get; set; }
        public virtual DbSet<order_statuses> order_statuses { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<payment_methods> payment_methods { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<reviews> reviews { get; set; }
        public virtual DbSet<suppliers> suppliers { get; set; }
        public virtual DbSet<deliveries> deliveries { get; set; }
        public virtual DbSet<inventory_batches> inventory_batches { get; set; }
        public virtual DbSet<discounts> discounts { get; set; }
        public virtual DbSet<bouquet_templates> bouquet_templates { get; set; }
        public virtual DbSet<employees> employees { get; set; }
    }
}
