//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_items
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int flower_id { get; set; }
        public int quantity { get; set; }
        public decimal price_at_time { get; set; }
    
        public virtual flowers flowers { get; set; }
        public virtual orders orders { get; set; }
    }
}
