//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int payment_method_id { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string status { get; set; }
        public string transaction_id { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual payment_methods payment_methods { get; set; }
    }
}
