//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int id { get; set; }
        public int flower_id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual flowers flowers { get; set; }
    }
}
